apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  namespace: default
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app-service
  endpoints:
  - interval: 5s
    targetPort: 8080
    path: /metrics